POST http://localhost:8080/v1/api/employee/customers/setProperties
Content-Type: application/json

{
  "customerId": 1,
  "gender": "MALE",
  "dateOfBirth": "1995-11-11"
}

###

POST http://localhost:8080/v1/api/employee/customers/addSale
Content-Type: application/json

{
  "customerId": 1,
  "shopId": 1,
  "paid": 15.75
}

###

PUT http://localhost:8080/v1/api/employee/giveOutFreeCup
Content-Type: application/json

{
  "customerId": 1,
  "shopId": 1
}

###