POST http://localhost:8080/v1/api/employee/customers/setProperties
Content-Type: application/json

{
  "customerId": 2,
  "gender": "MALE",
  "dateOfBirth": "1995-11-11"
}

###

POST http://localhost:8080/v1/api/employee/customers/addSale
Content-Type: application/json

{
  "customerId": 1,
  "shopId": 1,
  "paid": 0.75,
  "reason": "SALE"
}

###

PUT http://localhost:8080/v1/api/employee/giveOutFreeCup
Content-Type: application/json

{
  "customerId": 78347,
  "shopId": 278388
}

###