GET http://localhost:8080/v1/api/employee/statistics/getAvgCountCustomersByGender?gender=MALE
Content-Type: application/json

###

GET http://localhost:8080/v1/api/employee/statistics/getAvgCountCustomersByGender?gender=FEMALE
Content-Type: application/json

###


GET http://localhost:8080/v1/api/employee/statistics/getAvgCountCustomersByGender?gender=UNKNOWN
Content-Type: application/json

###


GET http://localhost:8080/v1/api/employee/statistics/getAvgCountCustomersByGender?gender=NOTGENDER
Content-Type: application/json

###


GET http://localhost:8080/v1/api/employee/statistics/getAverageBillByLastMonth?shopId=2
Content-Type: application/json

###

GET http://localhost:8080/v1/api/employee/statistics/getAvgCountCustomersByLastPeriod?shopId=2&period=MO
Content-Type: application/json

###