POST http://localhost:8080/v1/api/customer/registration
Content-Type: application/json

{
  "telegramId": 9
}

###

GET http://localhost:8080/v1/api/customer/9/profile
Content-Type: application/json

###

GET http://localhost:8080/v1/api/customer/724/monthlyReport
Content-Type: application/json

###