POST http://localhost:8080/v1/api/customer/registration
Content-Type: application/json

{
  "telegramId": 9
}

###

GET http://localhost:8080/v1/api/customer/7283/profile
Content-Type: application/json

###

GET http://localhost:8080/v1/api/customer/7234/monthlyReport
Content-Type: application/json

###